add batchModsTable & single row actions on batchTable
pieter-degeneffe/equibase pull request #21
Opened 2020-10-02 10:17 UTC by VercammenJens

2020-10-06 09:53 UTC, aHerbots requested changes

2020-10-06 09:53 UTC, aHerbots commented on src/views/stock/batch.vue
> +      <v-tab class="d-print-none" @change="setRefresh()">
zijn de () hier nodig?

2020-10-06 09:53 UTC, aHerbots commented on src/components/stock/BatchTable.vue
> +        <tr @click="selectRow(props.item)"
is het hier nodig om props.item mee te geven? kan je "selectRow" gebruiken?

2020-10-06 09:53 UTC, aHerbots commented on src/views/stock/batch.vue
> +      console.log('setRefresh: true');
console.log mag weg ;)

2020-10-06 11:33 UTC, VercammenJens commented on src/components/stock/BatchTable.vue
> +        <tr @click="selectRow(props.item)"
Ja want ik ga checken of dat die item in mijn selectedBatches zit of niet, als ik niets meegeef gebeurt er niets onclick

2020-10-07 08:12 UTC, aHerbots commented on src/components/stock/BatchTable.vue
> +        <tr @click="selectRow(props.item)"
ok!

2020-10-07 08:12 UTC, merged