Feature/server side products
pieter-degeneffe/equibase pull request #22
Opened 2020-10-05 12:31 UTC by VercammenJens

2020-10-06 09:57 UTC, aHerbots requested changes

2020-10-06 09:57 UTC, aHerbots commented on src/components/AppNavigation.vue
>                </v-list-item-action> -->
comment mag weg

2020-10-06 09:57 UTC, aHerbots commented on src/components/AppNavigation.vue
> +            <v-list-item v-for="(child, i) in item.submenu" :key="i" :to="child.url" class="pl-8">
gebruik je de i ergens?

2020-10-06 09:57 UTC, aHerbots commented on src/views/stock/batch.vue
> +      <v-tab class="d-print-none" @change="setRefresh()">
() nodig?

2020-10-06 11:38 UTC, VercammenJens commented on src/components/AppNavigation.vue
> +            <v-list-item v-for="(child, i) in item.submenu" :key="i" :to="child.url" class="pl-8">
Denk dat die i's zijn voor de key aan te wijzen, heb hier enkel de class toegevoegd voor subitems beter te onderscheiden van de hoofditems

2020-10-07 08:15 UTC, aHerbots commented on src/components/AppNavigation.vue
> +            <v-list-item v-for="(child, i) in item.submenu" :key="i" :to="child.url" class="pl-8">
klopt, sorry had de key="i" niet gezien

2020-10-07 08:25 UTC, merged